### ISSUE TITLE
Can't add my sentry key in v4 anymore.

### ISSUE THREAD

**Issue by x2pdenjo** [mentos1386/nest-raven#12]
app.module.ts
```ts
imports: [
  RavenModule.forRoot('https://somekey@sentry.io/someid'),
],
providers: [{
    provide: APP_INTERCEPTOR,
    useValue: new RavenInterceptor(),
}]
```

This his how it worked in Version 3 for Nest 5 for me.

Error with v4 for Nest 6:

> Property 'forRoot' does not exist on type 'typeof RavenModule'.

Documentation does not really help, there is nowhere mentioned where I add my Sentry API Key.

Thanks for any help.

**Comment by mentos1386** [comment]
Hej @x2pdenjo, sorry for the confusion.

[Version 3](https://github.com/mentos1386/nest-raven/releases/tag/3.0.0) introduced the [@sentry/minimal](https://github.com/getsentry/sentry-javascript/tree/master/packages/minimal) instead of raven lib. This means that you have to [setup sentry sdk yourself](https://github.com/mentos1386/nest-raven/tree/3.0.0#include-module). 

You can see how to do that by following the guide [here](https://docs.sentry.io/error-reporting/quickstart/?platform=node).

But basically, you should import sentry sdk `npm install @sentry/node@5.1.2` and make sure your `main.ts` (or wherever you initialise nestjs looks something like this:
```ts
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as Sentry from '@sentry/node'; // Import sentry

async function bootstrap() {
  Sentry.init({ dsn: 'https://<key>@sentry.io/<project>' }); // Initialise sentry

  const app = await NestFactory.create(AppModule);
  await app.listen(3000);
}
bootstrap();
```
